import Header from "@/components/Header"
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
